# Generated by Django 3.2.2 on 2021-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='andaman_and_nicobar_islands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=1024)),
                ('district_id', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('vaccine_date', models.DateField()),
                ('available_capacity', models.IntegerField()),
                ('vaccine', models.CharField(max_length=50)),
                ('status', models.CharField(default='DEFAULT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=1024)),
                ('district_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=1024)),
                ('state_id', models.IntegerField()),
            ],
        ),
    ]
