# Generated by Django 3.2.2 on 2021-05-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andhra_Pradesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=1024)),
                ('district_id', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('vaccine_date', models.DateField()),
                ('available_capacity', models.IntegerField()),
                ('vaccine', models.CharField(max_length=50)),
                ('status', models.CharField(default='DEFAULT', max_length=10)),
            ],
        ),
    ]
