# Generated by Django 3.2.2 on 2021-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_assam_bihar_chandigarh_chhattisgarh_dadra_and_nagar_haveli_daman_and_diu_delhi_goa_gujarat_haryana_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('district_id', models.IntegerField()),
                ('state_name', models.CharField(max_length=1024)),
            ],
        ),
    ]
