from vaccination.models import Andaman_and_nicobar_islands
from vaccination.models import Andhra_Pradesh
from vaccination.models import Arunachal_Pradesh
from vaccination.models import Assam
from vaccination.models import Bihar
from vaccination.models import Chandigarh
from vaccination.models import Chhattisgarh
from vaccination.models import Dadra_and_nagar_haveli
from vaccination.models import Daman_and_diu
from vaccination.models import Delhi
from vaccination.models import Goa
from vaccination.models import Gujarat
from vaccination.models import Haryana
from vaccination.models import Himachal_pradesh
from vaccination.models import Jammu_and_kashmir
from vaccination.models import Jharkhand
from vaccination.models import Karnataka
from vaccination.models import Kerala
from vaccination.models import Ladakh
from vaccination.models import Lakshadweep
from vaccination.models import Madhya_pradesh
from vaccination.models import Maharashtra
from vaccination.models import Manipur
from vaccination.models import Meghalaya
from vaccination.models import Mizoram
from vaccination.models import Nagaland
from vaccination.models import Odisha
from vaccination.models import Puducherry
from vaccination.models import Punjab
from vaccination.models import Rajasthan
from vaccination.models import Sikkim
from vaccination.models import Tamil_nadu
from vaccination.models import Telangana
from vaccination.models import Tripura
from vaccination.models import Uttar_pradesh
from vaccination.models import Uttarakhand
from vaccination.models import West_bengal