# Generated by Django 3.2.1 on 2021-05-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasma_topic_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasma_user_name', models.CharField(max_length=50)),
                ('social_media_content', models.CharField(max_length=1024)),
                ('social_media', models.CharField(max_length=25)),
                ('plasma_request_date', models.DateField()),
                ('plasma_topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidfeed.plasmatopic')),
            ],
        ),
    ]
