# Generated by Django 3.2.2 on 2021-05-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlasmaTopic',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='social_media_content',
            new_name='plasma_social_media_content',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='plasma_topic_name',
            new_name='topic_name',
        ),
        migrations.RemoveField(
            model_name='plasma',
            name='social_media',
        ),
        migrations.AddField(
            model_name='plasma',
            name='plasma_user_location',
            field=models.CharField(default='Mumbai', max_length=50),
        ),
    ]
