# Generated by Django 3.2.2 on 2021-05-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0002_auto_20210506_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_user_name', models.CharField(max_length=50)),
                ('oxygen_social_media_content', models.CharField(max_length=1024)),
                ('oxygen_request_date', models.DateField()),
                ('oxygen_user_location', models.CharField(default='Mumbai', max_length=50)),
                ('oxygen_topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidfeed.topic')),
            ],
        ),
    ]
