# Generated by Django 3.2.2 on 2021-05-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0003_oxygen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='oxygen_user_location',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='plasma_user_location',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_user_name', models.CharField(max_length=50)),
                ('bed_social_media_content', models.CharField(max_length=1024)),
                ('bed_request_date', models.DateField()),
                ('bed_user_location', models.CharField(default=' ', max_length=50)),
                ('bed_topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidfeed.topic')),
            ],
        ),
    ]
