# Generated by Django 3.2.2 on 2021-05-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0004_auto_20210506_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
