# Generated by Django 3.2.2 on 2021-05-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_status',
            field=models.CharField(default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='oxygen_status',
            field=models.CharField(default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='plasma',
            name='plasma_status',
            field=models.CharField(default='New', max_length=10),
        ),
    ]
