# Generated by Django 3.2.2 on 2021-05-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidfeed', '0006_auto_20210507_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_request_date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_social_media_content',
            new_name='social_media_content',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_topic_name',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_user_location',
            new_name='user_location',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='plasma_user_name',
            new_name='user_name',
        ),
    ]
